export * from "./Comment/args";
export * from "./Customer/args";
export * from "./Discount/args";
export * from "./Laptop/args";
export * from "./Person/args";
export * from "./Post/args";
export * from "./PriceMap/args";
export * from "./Purchase/args";
export * from "./User/args";
